theme: jekyll-theme-minimal
title: "Plugins & Addons - Construct 3"
google_analytics: UA-156817006-3

include:
  - _layouts


url: "https://c3plugins.stranianelli.com" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
# Plugins (previously gems:)
 # plugins:
 #   - jekyll-sitemap
#   - jekyll-gist
#   - jekyll-feed
#   - jekyll-include-cache
#   - jemoji

# mimic GitHub Pages with --safe
# whitelist:
  # - jekyll-sitemap
  # - jekyll-gist
  # - jekyll-feed
  # - jekyll-include-cache
